CREATE TABLE IF NOT EXISTS sessions (
  session_id         TEXT PRIMARY KEY,
  source_agent       TEXT DEFAULT 'agent',
  project            TEXT,
  started_at         TIMESTAMPTZ,
  ended_at           TIMESTAMPTZ,
  duration_minutes   INTEGER,
  title              TEXT,
  metadata           JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS layers (
  name                 TEXT PRIMARY KEY,
  description          TEXT NOT NULL,
  schema_file          TEXT NOT NULL DEFAULT 'schema.sql',
  access_mode          TEXT NOT NULL DEFAULT 'read-write',
  ingest_allowed       BOOLEAN NOT NULL DEFAULT true,
  is_coordination      BOOLEAN NOT NULL DEFAULT false,
  is_classifier_label  BOOLEAN NOT NULL DEFAULT false,
  alias_of             TEXT REFERENCES layers(name),
  added_by             TEXT NOT NULL DEFAULT 'kernel',
  deprecated           BOOLEAN NOT NULL DEFAULT false,
  lifecycle            TEXT NOT NULL DEFAULT 'curated',
  capabilities         JSONB NOT NULL DEFAULT '{}'::jsonb,
  since_version        TEXT
);

CREATE TABLE IF NOT EXISTS memories (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  layer            TEXT NOT NULL,
  content          TEXT NOT NULL,
  metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
  origin           TEXT NOT NULL CHECK (origin IN ('human', 'agent', 'cron')),
  source_agent     TEXT,
  source_session   TEXT REFERENCES sessions(session_id),
  source_sequence  INTEGER,
  project          TEXT,
  status           TEXT NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'pending', 'resolved')),
  supersedes       BIGINT REFERENCES memories(id),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exchanges (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id            TEXT REFERENCES sessions(session_id),
  exchange_number       INTEGER,
  is_after_compaction   BOOLEAN NOT NULL DEFAULT false,
  human_text            TEXT,
  agent_text            TEXT,
  human_timestamp       TIMESTAMPTZ,
  agent_timestamp       TIMESTAMPTZ,
  response_latency_ms   INTEGER,
  UNIQUE(session_id, exchange_number)
);

CREATE TABLE IF NOT EXISTS tool_uses (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id            TEXT REFERENCES sessions(session_id),
  exchange_number       INTEGER,
  tool_name             TEXT,
  tool_params_summary   TEXT,
  had_error             BOOLEAN NOT NULL DEFAULT false,
  error_message         TEXT,
  initiative_type       TEXT
);

CREATE TABLE IF NOT EXISTS thinking_blocks (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id            TEXT REFERENCES sessions(session_id),
  exchange_number       INTEGER,
  position_in_session   REAL,
  depth                 TEXT,
  caution_ratio         REAL,
  word_count            INTEGER,
  is_after_compaction   BOOLEAN NOT NULL DEFAULT false,
  full_text             TEXT
);

CREATE OR REPLACE VIEW layer_stats AS
SELECT l.name,
       COUNT(m.id) AS row_count,
       SUM(CASE WHEN m.id IS NOT NULL AND m.supersedes IS NULL THEN 1 ELSE 0 END) AS active_count
FROM layers l
LEFT JOIN memories m ON m.layer = l.name
GROUP BY l.name;

CREATE INDEX IF NOT EXISTS idx_memories_layer ON memories(layer);
CREATE INDEX IF NOT EXISTS idx_memories_status ON memories(status);
CREATE INDEX IF NOT EXISTS idx_memories_project ON memories(project);
CREATE INDEX IF NOT EXISTS idx_memories_origin ON memories(origin);
CREATE INDEX IF NOT EXISTS idx_memories_created_at ON memories(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_exchanges_session ON exchanges(session_id);
CREATE INDEX IF NOT EXISTS idx_tool_uses_session ON tool_uses(session_id);
CREATE INDEX IF NOT EXISTS idx_thinking_session ON thinking_blocks(session_id);
